### ISSUE TITLE
Nefunkční s aktuální verzí openTofu

### ISSUE THREAD

**Issue by RostakTom** [vpsfreecz/terraform-provider-vpsadmin#10]
Ahoj, 
zkoušel jsem rozjet terraform-provider-vpsadmin s aktuální verzí openTofu (fork terraformu) a u jakéhokoliv volání resource mi to píše chybu:
`# Declare a public key for connection over SSH
resource "vpsadmin_ssh_key" "my-key" {
  label = "My public key"

  key = file(var.ssh_public_key_path) // "~/.ssh/my_key.pub"
}`

`Planning failed. OpenTofu encountered an error while generating this plan.

╷
│ Error: Authentication failed: Action not found
│ 
│   with module.vps_test.provider["registry.terraform.io/vpsfreecz/vpsadmin"],
│   on ../../modules/vpsfree/main.tf line 13, in provider "vpsadmin":
│   13: provider "vpsadmin" {
│ 
╵`

Napadlo mě, že by to mohlo být neaktuálností této verze terraform-provider-vpsadmin, a že neodpovídá aktuální vpsadmin API.

Je nějaká šance, že by tento repositář aktualizovat, aby to fungovalo?

Mockrát díky za tuto tvorbu !

**Comment by aither64** [comment]
Je to tak, zrovna dneska odpoledne jsem navýšil verzi API, tak to teď nesedí. Vydám novou verzi providera.

**Comment by RostakTom** [comment]
Díky moc ! Je fakt skvělý, jak vpsFree neustále vylepšujete, a čím dál víc mi tento lidský přístup dává smysl podporovat před obchodníma gigantama ;)
Až bude nová verze, vyzkouším a podám report.

**Comment by aither64** [comment]
Díky za pochvalu :) Vydal jsem verzi 1.1.0, tak to můžeš vyzkoušet. Kdyby něco, tak dej vědět.

**Comment by RostakTom** [comment]
Šlape to ;)
