### ISSUE TITLE
Doesn't work with terraform v0.12

### ISSUE THREAD

**Issue by tom-kuca** [vpsfreecz/terraform-provider-vpsadmin#2]
Using terraform 0.12,  `apply` fails with an error message _Incompatible API version with plugin._

```
> terraform apply        

Error: Failed to instantiate provider "vpsadmin" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

```
> terraform version 
Terraform v0.12.9
```

Terraform provides a guide for upgrading providers to 0.12 at https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html. After applying following steps from the guide, the plugin works.

```
go get github.com/hashicorp/terraform@v0.12.0
go mod tidy
go mod vendor
```

I do not have experience with neither terraform nor go, I'm not sure it that's all what should be done.

**Comment by aither64** [comment]
Thanks, I've updated the client, provider and example configuration. Now it should work with terraform 0.12. Feel free to reopen this if there's still something broken.
