### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by zimbatm** [vpsfreecz/terraform-provider-vpsadmin#3]
Is the provider stable enough to get a release?

This would allow me to package the provider for nixpkgs.

**Comment by aither64** [comment]
Well, I'm not actually using this provider myself, so unless an issue is reported when I'm not aware of breaking it...

Does this repository contain everything necessary for you to make a package? If you can build it, I can tag a release.

**Comment by zimbatm** [comment]
Yeah, I already have the package ready to go, I just need a release. It can even be a point release if you don't think this is stable.

**Comment by aither64** [comment]
Ok, I've tagged v0.1.0.
