### ISSUE TITLE
"Resource is locked." after first machine is created / destroyed

### ISSUE THREAD

**Issue by tom-kuca** [vpsfreecz/terraform-provider-vpsadmin#4]
Operations `terraform apply` or `terraform destroy` fail with an error message

> Error: VPS creation failed: Resource is locked. Try again later.

when there are two machines in the configuration. Only one machine is created (destroyed).

* After first run, first machine is created (destroyed), the second one is not. Error is reported.
* After second run, second machine is created (destroyed), without any error.

Terraform configuration I used is at https://gist.github.com/tom-kuca/71905e1e3d75d80b4a1fef583ee2cc9b. Sample output is below:
```
...
vpsadmin_ssh_key.builder: Creating...
vpsadmin_ssh_key.home: Creating...
vpsadmin_ssh_key.builder: Creation complete after 0s [id=1510]
vpsadmin_ssh_key.home: Creation complete after 0s [id=1509]
vpsadmin_vps.builder: Creating...
vpsadmin_vps.titan: Creating...
vpsadmin_vps.builder: Still creating... [10s elapsed]
vpsadmin_vps.builder: Still creating... [20s elapsed]
vpsadmin_vps.builder: Still creating... [30s elapsed]
vpsadmin_vps.builder: Still creating... [40s elapsed]
vpsadmin_vps.builder: Creation complete after 45s [id=16181]

Error: VPS creation failed: Resource is locked. Try again later.

  on main.tf line 58, in resource "vpsadmin_vps" "titan":
  58: resource "vpsadmin_vps" "titan" {
```

The error message is printed immediately after the "Creation complete after 45s" without any delay.

I tried it on master branch a few times, the behavior was always the same.

**Comment by aither64** [comment]
Well, this is a limitation of our API. I don't see any way to fix this in the provider. Does `terraform apply -parallelism=1` help?

The thing is, when creating a VPS, vpsAdmin is recalculating resource usage and it locks the accounting object until the operation finishes... changes to the accounting object are done only when the operation succeeds, so without the locking, you could create as many VPS as you want. There's also another lock that would prevent parallel VPS creation in how user namespaces are handled on vpsAdminOS, that's bugging us even when migrating VPS.

**Comment by tom-kuca** [comment]
> Does `terraform apply -parallelism=1` help?

Yes.

That's perfectly fine solution. The only improvement I see is to tell users they should do it. If there is an error code in the response of the API, something like _RESOURCE_LOCKED_, the plugin can check the code and print a message suggesting `-parallelism=1` if it's present. 

Closing, I may check if it's possible later.
