### ISSUE TITLE
[doc] How to find valid vpsadmin_vps parameters?

### ISSUE THREAD

**Issue by zimbatm** [vpsfreecz/terraform-provider-vpsadmin#5]
When using a `vpsadmin_vps`, how do I find which values are valid for parameters such as `location` and `os_template`?

**Comment by zimbatm** [comment]
answer: Install the ruby client and run `vpsfreectl os_template list` or `vpsfreectl location list`

**Comment by zimbatm** [comment]
Regarding docs, the `get-token` utility generates a temporary token. It was surprising when the token stopped working after a few days.

**Comment by aither64** [comment]
Thanks, I've tried to describe it better in the example configuration, see 33cbffdae98798158c21c452acdcec35eac5eab6.

Regarding the tokens, it's written in readme. I'd rather the users create permanent tokens consciously.
