### ISSUE TITLE
Error: SSH key creation failed: input parameters not valid

### ISSUE THREAD

**Issue by zimbatm** [vpsfreecz/terraform-provider-vpsadmin#6]
For future users:

It took me a while to figure this one out. This error happens if the vpsadmin_ssh_key key contains multiple SSH keys.

**Comment by aither64** [comment]
Thanks for the feedback, I've [added it](https://github.com/vpsfreecz/terraform-provider-vpsadmin/commit/e557e815b503467e6a6df5cebd80b462cbfd3e6d) to the example configuration.
