### ISSUE TITLE
Publish the provider to the registry

### ISSUE THREAD

**Issue by zimbatm** [vpsfreecz/terraform-provider-vpsadmin#9]
Do you have any plans on publishing the provider to the registry?

A small head-up that as I am removing back-compat to terraform 0.12 in https://github.com/NixOS/nixpkgs/pull/155477, I am converting all providers to be using either the registry, or remove them otherwise.

**Comment by aither64** [comment]
I suspect I'll have to learn what's new with terraform >0.12 and bring the provider up-to-date. I'll try to publish it once that's done.

**Comment by zimbatm** [comment]
The main thing is that you will need a GPG key so sign and release the provider. You can steal the github actions workflow from here: https://github.com/numtide/terraform-provider-secret/tree/master/.github/workflows

**Comment by aither64** [comment]
Done! Updated and published at https://registry.terraform.io/providers/vpsfreecz/vpsadmin/latest.
